# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: elude visibility
description: BS-X, Prototype, Unreleased & Other Unique ROMs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eludevisibility.org" # the base hostname & protocol for your site

# Build settings
exclude:
  - README.md
  - Gemfile*
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
highlighter: 'pygments'
permalink: /:year/:title
gzip_zopfli: true
gems:
  - jekyll-assets
assets:
  cachebust: none
  debug: false
  assets:
    - "*.png"
  js_compressor: uglifier
  css_compressor: sass
  gzip:
    - text/css
    - application/javascript
    - image/svg+xml
    - image/vnd.microsoft.icon
    - image/x-icon
  sources:
    - _assets/files
