# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Settings
title: elude visibility
description: BS-X, Prototype, Unreleased & Other Unique ROMs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eludevisibility.org" # the base hostname & protocol for your site
paginate: 5
paginate_path: "/page/:num/"
locale: en_US

# Build Settings
incremental: false
profile: false
exclude:
  - README.md
  - Gemfile*
  - d.php
  - u.php
  - files/
  - node_modules/
  - .jekyll-metadata
  - .DS_Store
  - package.json
  - package-lock.json
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
highlighter: 'pygments'
permalink: /:year/:title
gzip_zopfli: true
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-sitemap
plugins: [jekyll-paginate, jekyll-assets, jekyll-last-modified-at, jekyll-sitemap]
assets:
  source_maps: false
  compression: false
  gzip: false
  caching:
    enabled: false
    path: ".jekyll-cache/assets"
    type: file
  defaults:
    integrity:
      {css,img,js}: false
  sources:
    - _assets/files
