# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Settings
title: elude visibility
description: BS-X, Prototype, Unreleased & Other Unique ROMs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eludevisibility.org" # the base hostname & protocol for your site
paginate: 5
paginate_path: "/page/:num/"
locale: en_US

# Build Settings
incremental: false
profile: false
exclude:
  - README.md
  - Gemfile*
  - d.php
  - u.php
  - files/
  - node_modules/
  - .jekyll-metadata
  - .DS_Store
  - package.json
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
highlighter: 'pygments'
permalink: /:year/:title
gzip_zopfli: true
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-press
  - jekyll-last-modified-at
  - jekyll-sitemap
assets:
  cachebust: none
  debug: false
  digest: false
  assets:
    - "*.png"
    - "*.jpg"
  js_compressor: uglifier
  css_compressor: sass
  gzip:
    - text/css
    - application/javascript
    - image/svg+xml
    - image/vnd.microsoft.icon
    - image/x-icon
  sources:
    - _assets/files
jekyll-press:
  exclude: ['feed.xml', '_assets/images/*'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
